[package]
name = "leptos-tutorial"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
gloo-timers = "0.3.0"
leptos = { version = "0.7.4", features = ["csr"] }
leptos_meta = "0.7.4"
wasm-bindgen = "0.2.100"
